name = "waffle's Pack (OptiFine)"
author = "wafflecoffee"
version = "2021.5.10"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43dfdca67c31f69ca95bab0e6b56ed17b91ad0ece9037ee299f6891423a7fc66"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
