name = "waffle's Mods (Snapshot)"
author = "wafflecoffee"
version = "2021.04.29"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a729ac2f65efd940ceefcadc0fd843ff1dbb799704eb551a68041a5b132fcf62"

[versions]
fabric = "0.11.3"
minecraft = "21w17a"
