name = "waffle's Mods (Snapshot)"
author = "wafflecoffee"
version = "2021.04.27"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90362d449d6257bfd8fce5819824b9f0f6e5b424c3f873347fb4c814656931f6"

[versions]
fabric = "0.11.3"
minecraft = "21w16a"
