name = "waffle's Mods (Snapshot)"
author = "wafflecoffee"
version = "2021.04.27"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "116086ca550c43a22b2c2676424678a0dac3e1ef6ada9e13991fb227480e41d0"

[versions]
fabric = "0.11.3"
minecraft = "21w16a"
