name = "waffle's Pack (OptiFine)"
author = "wafflecoffee"
version = "2021.4.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12b4b359c8c6ef67666aacd419fee246fc34ffc69d051a063a3693f9b1e019db"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
