name = "waffle's Pack (OptiFine)"
author = "wafflecoffee"
version = "2021.4.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bc224bfe14e874e8aedbaef1094c6373758006ac7037b795486dae3e445ad9e"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
