name = "waffle's Pack (OptiFine)"
author = "wafflecoffee"
version = "20210327-1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eb420264adb525df6cef0974270204083842003f51a17ab3eeb428a8f137b33"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
