name = "waffle's Pack (OptiFine)"
author = "wafflecoffee"
version = "2021.4.29"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "912a9fedbf28b5d2480cdc13e4cbaaa31280601a9de92ee8231babfa534f7afd"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
