name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "2021.5.20"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c64729d2ee222d4f95e6e35cfe2968db4621bd7adfbd27d0607d0bacba155c5c"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
