name = "waffle's Pack (Sodium Modified)"
author = "wafflecoffee"
version = "2021.5.19"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f619c150227ab8e2dc8c9b9c29b9f9102725b96012e717fdf164d2dc9e8f04ef"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
