name = "waffle's Pack (Sodium Modified)"
author = "wafflecoffee"
version = "2021.5.10"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ad7170d08a057399a698a16fda53f7fb533fe3ed90397d53c07db754f90fc43"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
