name = "waffle's Pack (Sodium Modified)"
author = "wafflecoffee"
version = "2021.5.19"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfac4ecb3f70767ad70e2f0151fa5aa3c13c940ca94b319e50697bb06cb44589"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
