# The configuration file for Shut Up Console

[shutupconsole]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = [
  "Received passengers for unknown entity",
  "No uniform exists with name:",
  "Unsupported uniform:",
  "Failed to parse the block ID map",
  "- There is no block with the name",
  "Unable to resolve texture due to reference chain",
  "Unable to resolve texture reference",
  "Method overwrite conflict for",
  "does not exist, attempting to use an alternative icon",
  "has a broken icon, loading default icon",
  "ERROR : Couldn't load Narrator library : Unable to load library",
  "########## GL ERROR ##########",
  "@ Pre render",
  "65539: Invalid key -1",
  "This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.",
  "false for blockstate",
  "java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!",
  "at java.desktop/sun.awt.image.ByteInterleavedRaster.getDataElements(ByteInterleavedRaster.java:313)",
  "at java.desktop/java.awt.image.BufferedImage.getRGB(BufferedImage.java:917)",
  "at xaero.map.MapWriter.loadBlockColourFromTexture(MapWriter.java:718)",
  "at xaero.map.region.MapPixel.getPixelColours(MapPixel.java:44)",
  "at xaero.map.region.MapBlock.getPixelColour(MapBlock.java:48)",
  "at xaero.map.region.MapTileChunk.updateBuffers(MapTileChunk.java:80)",
  "at xaero.map.region.texture.LeafRegionTexture.preUpload(LeafRegionTexture.java:44)",
  "at xaero.map.MapProcessor.onRenderProcess(MapProcessor.java:415)",
  "at xaero.map.events.Events.handleRenderTick(Events.java:88)",
  "at net.minecraft.class_374.handler$cal000$onDraw(class_374.java:517)",
  "at net.minecraft.class_374.method_1996(class_374.java:40)",
  "at net.minecraft.class_310.method_1523(class_310.java:1114)",
  "at net.minecraft.class_310.method_1514(class_310.java:728)",
  "at net.minecraft.client.main.Main.main(Main.java:217)",
  "at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
  "at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)",
  "at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
  "at java.base/java.lang.reflect.Method.invoke(Method.java:567)",
  "at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)",
  "at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)",
  "at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)",
  "at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
  "at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)",
  "at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
  "at java.base/java.lang.reflect.Method.invoke(Method.java:567)",
  "at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)",
  "at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)",
  "at org.multimc.EntryPoint.listen(EntryPoint.java:143)",
  "at org.multimc.EntryPoint.main(EntryPoint.java:34)",
  "Applied 0 biome modifications to 0 of 81 new biomes in",
  "WTHIT is not found on the server, all syncable config will reset to their default value.",
  "@ Post render",
  ".lr loaded"
]

# If a log message matches one of these regex patterns, it will be filtered out from logging
regex = []
