# The configuration file for Shut Up Console

[shutupconsole]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["Received passengers for unknown entity",
"No uniform exists with name:",
"Unsupported uniform:",
"Failed to parse the block ID map",
"- There is no block with the name",
"Unable to resolve texture due to reference chain",
"Unable to resolve texture reference",
"Method overwrite conflict for",
"does not exist, attempting to use an alternative icon",
"has a broken icon, loading default icon",
"ERROR : Couldn't load Narrator library : Unable to load library"]

# If a log message matches one of these regex patterns, it will be filtered out from logging
regex = []
