name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.21"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4271bb963c5fddf8683b0d7e119becff14329c1803e870e21082f92c629c0a73"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
