name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.7.27"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "040ca2ecf199bba77fe71dc963b71a90fc7dfbad6f9754945ea1db7af345d5d5"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
