name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e0ae84affd5635725be45c1b4d2dd17f4d58285af85d05be5adc6227f476363"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
