name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.12.10"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c0bb08218824e109f9016bc929be4851b8c0d4f3ba7f0146e7e371f5ce64b37"

[versions]
fabric = "0.12.11"
minecraft = "1.17.1"
