name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b40712fa87c859e4f14ac29c79469cd14ec519d3e3e51eef4d1c75771e1b06"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
