name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.9.29"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4f8abe8b7a0efafc49464ffc32b23e09e5a2dd7b12ad0a51ab5173362870a4c"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
