name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.12.14"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e06f69ad9419def5749da46c66e1cf08dd7db40c23b38a353330d489249ccfc"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
