name = "waffle's Modpack"
author = "wafflecoffee"
version = "2022.1.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8c8c96cf5f2b83188d31180a09a8c5e7d36bda81d2da557ef657bd37d35076b"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
