name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23840620f574f7bff83230fe97692a68a842c5d604b842de8290d2802b7affe8"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
