name = "waffle's Modpack"
author = "wafflecoffee"
version = "2022.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76ddf69352ba3a607ef9a3c23962d697d98d5f65e490aa4740c14b07ca5697b7"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
