name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.7.20"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77608ce98d4a32f1c35c31dbb804dba2ff63326e7181e1cb34694059edf728de"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
