name = "waffle's Modpack"
author = "wafflecoffee"
version = "2022.1.9"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43d0fdaa3861c143fe71587a630dd5f382818051321c4079530efcfb9e410869"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
