name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.7.19"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4865abd7e7d9b75f1842c0cbce709b03897e0e87b13f83d060e9e8a2ec14685"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
