name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.11.14"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4adf33cfc62e7846b9686c8e1fb8ec514943b9414078efc84baebc26dae88d3b"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
