name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.9.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b13a6c693f568c33441ea9d736ea3634be7c7b5d3fc0be05852b20d88ccd1a"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
