name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.8.22"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "476330cd6dcc24c3a85697f1b7f3ecb81f2a6ee4b3570b48e9394b4772617823"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
