name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.30"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07df5171a71cfdfc2f496c11678976a4430ed250198c50ca6f6d8b79fab51dd6"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
