name = "waffle's Modpack"
author = "wafflecoffee"
version = "2022.1.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d11d4896892aa0f0bd29ff6048636454c9030f2475983fefbda3b8c35411c8a"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
