name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.7.20"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d6caa693eb008d5ae3563ef4703e9bb4af588090a345d38361b56b76a3b9345"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
