name = "waffle's Modpack"
author = "wafflecoffee"
version = "2022.1.13"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a4143de709daf56354fb184b955174232c1d253ee78384d794e3f62c4adc013"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
