name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.7.19"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beba2f47a8ea15721adcf6f77bdd05c295eb8646b5e4e95363c00afcefc2ca16"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
