name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca3f56088acd88c5483a938b05117d82bb64bd91a12b88fe41726199c8abbdd5"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
