name = "waffle's Modpack"
author = "wafflecoffee"
version = "2022.1.10"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d90b8556ba18cd471fd348b1b9edf4bd73e497bec06d65cdb62dc0a829671399"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
