name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.16"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20be1754d43109ffbf33ad3a6d0799baa94a51160d3d40be67a27df140c64e9b"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
