name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.12.02"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53a1e3c67fd8fede17c70982ed8073ce49a0613e97346cb1acfe8a9ea2373c98"

[versions]
fabric = "0.12.8"
minecraft = "1.17.1"
