name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.8.30"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2838c511d2a2f6f2719ea35f3c9e3e47f2dd723965dc9a23323f96df3e57bf16"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
