name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.8.30"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbf98bd433ef4449b1954f969ff8d4009cc09292b0e60ae6ac1944be07c00893"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
