name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.16"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3467323e928ef7d8726b6d16cbeb11b794587941eea7cc9621ae6aeb97ca7abd"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
