name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.7.14"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb942cd8cda8e8666615e768946caef1f0b3092bfb17449adb8316e3446492da"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
