name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.15"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14cb2fd4a9bae3e6465574c4e9e1291004d47191fd03910929fbf8736d3fa3e1"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
