name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.11.28"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "926de62b83b510575b72122babeb2c40fafb1fd17b40509e8211b2cee8da7952"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
