name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.9.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b191a30e00968b2b2e79cbf7b03a6755dbde8144ace0cfa1d1dd28537e9fcc90"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
