name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4155c418a978f4f009f605c14e82390712702909f8d52a2ba4def08450d08070"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
