name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.9.30"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a5fca17c9846e86d31f8a1c11c95fc3ee81a4a3e9f98e1cb3ddfca86e192e5b"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
