name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.9.9"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55f616b33fd1309af2d65039cc9275957e7fe0731f7366ff91555f5afb1a8093"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
