name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.9"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0100e85adf11fae4a100cf5161ad302a6c3b4d241af939349cf12c24093549a6"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
