name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.13"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f136856ad91a642aade3ca4c1e1d2a35d9d5a44e79014ae3f55fc22a668b7178"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
