name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.6.14"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d7e21e1b234e90b44b4f6ad5efb0fe3f3ab2afabf2bd63fadc6fc8b6edf79aa"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
