name = "waffle's Pack"
author = "wafflecoffee"
version = "2021.5.26"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "346467cb266556b65f9eb9347f4f24482e7d4145f35bcfe0bb183b458f5b55eb"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
