name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed3cf737d2225d7a62c58f70a6279414f6d95255cbbbbbaeac16f033fb194750"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
