name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.13"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb2f1c170a4c0a1f45d8cf24c394c3f04d0895037a28a7067482f25721c0e12e"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
