name = "waffle's Modpack"
author = "wafflecoffee"
version = "2022.1.11"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da9e34fcc71b77e282b1c99c1c10c2ab5d2f9bbd3cc0afa9068892aae66dc226"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
