name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.9.26"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce19ecf5cba969bc7a7af8f86103c72f1f6c77f95f00652cc87a6abaaba80eb9"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
