name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.11.13"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "134b087a5e7a5cd856022ba540a703f0520765080bccce545e9ee4eaab3e69da"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
