name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.10.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5f77c02c5961099cf58abeb17a5d5917edc2fd96e50d690ca1becc3928f3a9e"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
