name = "waffle's Modpack"
author = "wafflecoffee"
version = "2021.11.20"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06daa6e36b2f259b08c02ae045f0bcceaa7abbb098ffac25b0261f0eaebf8e3e"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
