name = "waffle's Pack (Sodium Modified)"
author = "wafflecoffee"
version = "2021.5.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37b996b4de2c5863ebe9cd0a0a9ef1ceba2d487eaceb411ed867cff22045f035"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
