name = "waffle's Pack (Sodium Modified)"
author = "wafflecoffee"
version = "2021.5.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0e44a5a672401ce7896c96561be8ee5472d981cbb421b8dedb79207b1e82cb5"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
