name = "waffle's Pack (Sodium Modified)"
author = "wafflecoffee"
version = "2021.5.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2aee141e5c362eb135ed36c32950aeb355be4b991e3645f28d11a8b25a8e88b"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
