name = "Origins Modlist for Da Blessed"
author = "DreamyFeather and wafflecoffee"
version = "4.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9fa47f7350b206a5bd3af9bef7e133c5f5469ca24c6d2ee1410a6522cd6e0eb"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
