name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "20210327-1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8a2ae0aa7bb59f4d2e9a71d67432bf4d7ab3807ddbbb42fa8d08412b14fec8d"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
