name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "2021.4.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21ed42529de6917f00d077b4e035e40802535671a5dc8fd68b68b9430eee8429"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
