name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "2021.4.29"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6b4b70ca2a4a930055a296abbf52281397e31bc93999533c88040ecaa79a6de"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
