name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "2021.4.10"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9017bf63d73019f4a5285bb28c33f3cfef6b4839fc00aec6297a8e79eebfe92a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
