name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "2021.5.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "500e7bc1def6b83970431ae82596efd387d725b640bac2f51603a65b2216b89e"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
