name = "waffle's Pack (Iris)"
author = "wafflecoffee"
version = "2021.5.21"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbc184e1510955e0fb059f340ff0027818b28d3a7de5a60564fed390fe5f3ba1"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
