name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "2021.5.21"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9b6b47c8f06708f13fff0ded411611adbbfa5560e08d57b3c20343aac74ff79"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
